### ISSUE TITLE
GSOC 2018 final report for evaluation

### ISSUE THREAD

**Issue by datakurre** [collective/collective.ifttt#58] opened 2018-07-23 08:29 UTC
GSOC requires student to produce final report as single document with pointers to all their contributions.

Because we have made all contributions through pull requests and this project has already wiki enabled, it probably makes sense for @Shriyanshagro to make the report as a new wiki page that lists and explains all his pull requests.

**Comment by datakurre** [comment] 2018-07-23 12:17
https://developers.google.com/open-source/gsoc/help/work-product

**Comment by skleinfeldt** [comment] 2018-07-23 13:43
Quoting from the GSoC email to mentors:

> As part of their final evaluations, students will provide a single URL to the code they produced. Then, as part of their final evaluation of the student, mentors will validate the target of the URL (provided in the evaluation), making sure it points to the GSoC 2018 work product. Mentors will also make sure the code compiles and there is adequate documentation provided for the work the student has completed.

This is due by August 14, but we should have a draft of the wiki page by August 6 so we have time to review.

**Comment by datakurre** [comment] 2018-08-07 12:39
@Shriyanshagro Example `~/.pypirc`

```
[distutils]                                                                                                                            
index-servers =
    pypi

[pypi]
username: YOUR_USERNAME
password: YOUR_PASSWORD
```

**Comment by datakurre** [comment] 2018-08-07 12:42
> The target of the link should contain a short description of what work was done, what code got merged, what code didn't get merged, and what's left to do.

**Comment by datakurre** [comment] 2018-08-07 12:43
> Create a blog post or web page or public GitHub gist that describes the work you've done and links to the commits you've made and repositories you've worked on. If there is still work to be done on the project, include that too. You can also share highlights or challenging pieces.
> 
>     ❗ This is the best option because it allows you to easily include a lot of information. This is good because it will clearly show what work you did, as well as make it easy for others to use and understand your code.
>

**Comment by skleinfeldt** [comment] 2018-08-09 12:52
Comments on final report so far.

Insert a heading "Get the Code" after the first sentence.

Fix or eliminate second sentence under "Abstract", don't know what you mean by "checks or conditions" and you have not supported these terms with an example.

First sentence under "Motivation": I think most would argue that content rules are very extensible, the problem is that they are not easy for non-programmers to use. Your add-on makes it really easy to create IFTTT triggers in Plone w/o having to understand content rules. I think you've built a very specific solution for IFTTT, not a generalized solution. It is a generalized problem, and your specific solution can be used as a template to create other specific solutions, like for Zapier.

I love the table. Maybe you should put a link to specific code for the automated testing and QA rows? (Since I assume there are not PRs)

Nitpick: "explained what the RSS URL are" => "explained what the RSS URL is"

Example IFTTT Applet: remove reference to Mountaineers.org since we only used the staging site and mostly used them to help review the docs. Under the Acknowledgements section you could thank Jeff Bowman of The Mountaineers for help reviewing documentation on Plone RSS feeds. IIRC the example applet that ultimately worked was from a Times of India public feed, mention that instead of Mountaineers here.

Event trigger Implementation Detail uses plural of content rules and actions - but there is only one content rule created right? So this should be singular. (If in fact there are multiple ones, never mind this comment!)

Acknowledgements: add Nejc's last name, Zupan.

Under Open Issues and Missing work you could mention that your project only covers Plone acting as an IFTTT trigger, not an IFTTT action. To support incoming requests from IFTTT to Plone we would need to implement OAuth2 and an IFTTT specific HTTP API, we decided this was out of scope. But this could be an idea for next year's GSoC.

**Comment by Shriyanshagro** [comment] 2018-08-09 13:49
@skleinfeldt @datakurre I have incorporated changes based on feedback. 
Other than that I was thinking of making the `missing work` visible at some other place as well (maybe at issues or readme) which would be helpful for future development.

**Comment by datakurre** [comment] 2018-08-09 15:23
@Shriyanshagro Missing work as issues sounds like good idea.

**Comment by Shriyanshagro** [comment] 2018-08-09 18:26
@skleinfeldt @datakurre report is completed from my side.  Kindly review it.
Should I add the demo site link on the report?

**Comment by datakurre** [comment] 2018-08-09 18:48
It’s better to leave demosite out of the report. It is temporary.

**Comment by datakurre** [comment] 2018-08-09 18:48
It’s better to leave demosite out of the report. It is temporary.

**Comment by datakurre** [comment] 2018-08-09 18:49
Closed accidentally. The report is ok for me, but I net Sally to close this once she is ok with the nuances :)

**Comment by skleinfeldt** [comment] 2018-08-09 22:27
Looks good to me!

**Closed by skleinfeldt** 2018-08-09 22:27 UTC
